services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DATABASE_API_KEY=playwright-gemini-secret-key-change-in-production
      - DATABASE_API_KEY=playwright-gemini-secret-key-change-in-production
      - DATABASE_URL=file:./prisma/dev.db
      - NEXT_PUBLIC_SKIP_DB_CHECKS=false
    volumes:
      - ../ai-test-management-db/dev.db:/app/prisma/dev.db
      - ../ai-test-management-playwright-projects:/app/playwright-projects