version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /home/ubuntu/ai-test-management-db/dev.db:/app/prisma/dev.db
      - /home/ubuntu/ai-test-management-playwright-projects:/app/playwright-projects
    command: >
      sh -c "mkdir -p /app/prisma/prisma && npm start"