services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=playwright-gemini-secret-key-change-in-production
    command: >
      sh -c "/usr/local/bin/reset-db.sh --reset && npm start"