version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /home/ubuntu/ai-test-management-db:/app/prisma/prisma
    command: >
      sh -c "mkdir -p /app/prisma/prisma && npm start"