version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_DATABASE_API_KEY=playwright-gemini-secret-key-change-in-production
      - DATABASE_API_KEY=playwright-gemini-secret-key-change-in-production
    volumes:
    #  - /home/ubuntu/ai-test-management-db/dev.db:/app/prisma/dev.db
      - /home/ubuntu/ai-test-management-playwright-projects:/app/playwright-projects