services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=playwright-gemini-secret-key-change-in-production
    volumes:
      - ../playwright-projects:/app/playwright-projects
      - ../data:/app/prisma
    command: >
      sh -c "mkdir -p /app/prisma && /usr/local/bin/reset-db.sh --reset && npm start"