name: Deploy to Self-Hosted Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Stop existing containers
        run: |
          docker-compose down || true

      - name: Pull latest images
        run: |
          docker-compose pull

      - name: Start application
        run: |
          docker-compose up -d

      - name: Wait for application to be ready
        run: |
          timeout=300
          until curl -s http://localhost:3000 > /dev/null || [ $timeout -eq 0 ]; do
            echo "Waiting for application to be ready..."
            sleep 5
            timeout=$((timeout-5))
          done
          if [ $timeout -eq 0 ]; then
            echo "Application failed to start within the timeout period"
            exit 1
          fi
          echo "Application is ready!" 
